<a href="https://colab.research.google.com/github/crownvamsi/ML/blob/main/Evaluating_all_Regression_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Multiple Linear Regression

###Import all the necessary libraries

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


## Read the datasets into python

In [24]:
df = pd.read_csv('Data.csv')
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
print(x[:5,:])
print('\n')
print(y[:5])

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 [  20.86   57.32 1010.24   76.64]
 [  10.82   37.5  1009.23   96.62]]


[463.26 444.37 488.56 446.48 473.9 ]


## Split the data into train and test split

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=0)


## Import the Linear Regression class for fitting the right model

In [26]:
from sklearn.linear_model import LinearRegression
lrmodel = LinearRegression()
lrmodel.fit(x_train, y_train)
resultlr = lrmodel.predict(x_test)
resultlr = resultlr.reshape(len(resultlr),1)
y_test_mr = y_test.reshape(len(y_test),1)
np.set_printoptions(precision=2)
print(np.concatenate((y_test_mr,resultlr),1))

[[431.23 431.43]
 [460.01 458.56]
 [461.14 462.75]
 ...
 [473.26 469.52]
 [438.   442.42]
 [463.28 461.88]]


##Import polynomial regression to test the same dataset

In [27]:
from sklearn.preprocessing import PolynomialFeatures
pnrmodel = PolynomialFeatures(degree = 4)
x_poly = pnrmodel.fit_transform(x_train)
x_poly2 = pnrmodel.fit_transform(x_test)
lrmodel2 = LinearRegression()
lrmodel2.fit(x_poly, y_train)
pnrresult = lrmodel2.predict(x_poly2)
print(np.concatenate((y_test_mr, pnrresult.reshape(len(pnrresult),1)),1))

[[431.23 433.94]
 [460.01 457.9 ]
 [461.14 460.52]
 ...
 [473.26 469.53]
 [438.   438.27]
 [463.28 461.66]]


##Import SVR from SVM to train the model

In [28]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
Y_train = y_train.reshape(len(y_train),1)
X_train = sc_x.fit_transform(x_train)
Y_train = sc_y.fit_transform(Y_train)
from sklearn.svm import SVR
svrmodel = SVR(kernel='rbf')
svrmodel.fit(X_train, Y_train)
svrresult = sc_y.inverse_transform(svrmodel.predict(sc_x.transform(x_test)))
svrresult = svrresult.reshape(len(svrresult),1)
print(np.concatenate((y_test_mr, svrresult),1))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[431.23 434.05]
 [460.01 457.94]
 [461.14 461.03]
 ...
 [473.26 470.6 ]
 [438.   439.42]
 [463.28 460.92]]


##Import Deceision Tree Regresion

In [29]:
from sklearn.tree import DecisionTreeRegressor
dtrmodel = DecisionTreeRegressor(random_state=0)
dtrmodel.fit(x_train, y_train)
dtrresult = dtrmodel.predict(x_test)
dtrresult = dtrresult.reshape(len(dtrresult),1)
print(np.concatenate((y_test_mr,dtrresult),1))

[[431.23 431.28]
 [460.01 462.81]
 [461.14 460.06]
 ...
 [473.26 471.46]
 [438.   437.76]
 [463.28 462.55]]


## Import Randomforest Model

In [30]:
from sklearn.ensemble import RandomForestRegressor
rfrmodel = RandomForestRegressor(n_estimators = 10, random_state=0)
rfrmodel.fit(x_train,y_train)
rfrresult = rfrmodel.predict(x_test)
rfrresult = rfrresult.reshape(len(rfrresult),1)
print(np.concatenate((y_test_mr, rfrresult),1))

[[431.23 433.78]
 [460.01 457.99]
 [461.14 463.14]
 ...
 [473.26 470.16]
 [438.   439.51]
 [463.28 460.32]]


## Evaluating all models using R - Squared

In [36]:
from sklearn.metrics import r2_score
print('Linear Regression R-Squared         :', r2_score(y_test_mr, resultlr))
print('Polynomial Regression R-Squared     :',r2_score(y_test_mr, pnrresult))
print('Support Vector Regression R-Squared :',r2_score(y_test_mr, svrresult))
print('Decision Tree Regression R-Squared  :',r2_score(y_test_mr, dtrresult))
print('Random Forest Regression R-Squared  :',r2_score(y_test_mr, rfrresult))

Linear Regression R-Squared         : 0.9325315554761302
Polynomial Regression R-Squared     : 0.9458192606428147
Support Vector Regression R-Squared : 0.9480784049986258
Decision Tree Regression R-Squared  : 0.9226091050550043
Random Forest Regression R-Squared  : 0.9615980699813017


## Conclusion


### The above R-Squared suggest that the best fitting model is Random forest regression model